# Actuator metrics expose for monitoring
# management.endpoints.web.exposure.include=*
management.endpoints.web.exposure.include=health,info,metrics,prometheus
spring.application.name=springapp
# Active profile using application-<>.properties
spring.profiles.active=dev
# Server Port
server.port=8080