# Actuator metrics expose for monitoring
# management.endpoints.web.exposure.include=*
management.endpoints.web.exposure.include=health,info,metrics,prometheus
spring.application.name=springapp
# Active profile using application-<>.properties
spring.profiles.active=stage
# Server Port
server.port=8080
# Properties for thymeleaf for rendering the templates html files.
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html