apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  {{-toYaml .Values.service.serviceType | nindent 2}}
  selector:
    app: {{ .Values.deploymenttype.labels }}  # Ensure labels are formatted as a map
  ports:
    - protocol: TCP
      port: {{ .Values.deploymenttype.containerPort }}
      targetPort: {{ .Values.deploymenttype.containerPort }}